package POJOS;
// Generated Mar 27, 2018 5:52:23 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Ad generated by hbm2java
 */
public class Ad  implements java.io.Serializable {


     private Integer idad;
     private User user;
     private String category;
     private String title;
     private String description;
     private Double price;
     private String location;
     private Date date;
     private String brand;
     private String image;
     private String image1;
     private String image2;
     private String image3;

    public Ad() {
    }

	
    public Ad(User user) {
        this.user = user;
    }
    public Ad(User user, String category, String title, String description, Double price, String location, Date date, String brand, String image, String image1, String image2, String image3) {
       this.user = user;
       this.category = category;
       this.title = title;
       this.description = description;
       this.price = price;
       this.location = location;
       this.date = date;
       this.brand = brand;
       this.image = image;
       this.image1 = image1;
       this.image2 = image2;
       this.image3 = image3;
    }
   
    public Integer getIdad() {
        return this.idad;
    }
    
    public void setIdad(Integer idad) {
        this.idad = idad;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getCategory() {
        return this.category;
    }
    
    public void setCategory(String category) {
        this.category = category;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getImage1() {
        return this.image1;
    }
    
    public void setImage1(String image1) {
        this.image1 = image1;
    }
    public String getImage2() {
        return this.image2;
    }
    
    public void setImage2(String image2) {
        this.image2 = image2;
    }
    public String getImage3() {
        return this.image3;
    }
    
    public void setImage3(String image3) {
        this.image3 = image3;
    }




}


