package POJOS;
// Generated Apr 2, 2018 10:11:49 PM by Hibernate Tools 4.3.1



/**
 * Contact generated by hbm2java
 */
public class Contact  implements java.io.Serializable {


     private Integer idcontact;
     private String name;
     private String email;
     private Integer adid;
     private String phone;
     private String msg;
     private String attachment;

    public Contact() {
    }

    public Contact(String name, String email, Integer adid, String phone, String msg, String attachment) {
       this.name = name;
       this.email = email;
       this.adid = adid;
       this.phone = phone;
       this.msg = msg;
       this.attachment = attachment;
    }
   
    public Integer getIdcontact() {
        return this.idcontact;
    }
    
    public void setIdcontact(Integer idcontact) {
        this.idcontact = idcontact;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getAdid() {
        return this.adid;
    }
    
    public void setAdid(Integer adid) {
        this.adid = adid;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getMsg() {
        return this.msg;
    }
    
    public void setMsg(String msg) {
        this.msg = msg;
    }
    public String getAttachment() {
        return this.attachment;
    }
    
    public void setAttachment(String attachment) {
        this.attachment = attachment;
    }




}


