package POJOS;
// Generated Mar 27, 2018 5:52:23 PM by Hibernate Tools 4.3.1



/**
 * Faq generated by hbm2java
 */
public class Faq  implements java.io.Serializable {


     private Integer idfaq;
     private String question;
     private String answer;

    public Faq() {
    }

    public Faq(String question, String answer) {
       this.question = question;
       this.answer = answer;
    }
   
    public Integer getIdfaq() {
        return this.idfaq;
    }
    
    public void setIdfaq(Integer idfaq) {
        this.idfaq = idfaq;
    }
    public String getQuestion() {
        return this.question;
    }
    
    public void setQuestion(String question) {
        this.question = question;
    }
    public String getAnswer() {
        return this.answer;
    }
    
    public void setAnswer(String answer) {
        this.answer = answer;
    }




}


