package POJOS;
// Generated Mar 27, 2018 5:52:23 PM by Hibernate Tools 4.3.1



/**
 * Feedback generated by hbm2java
 */
public class Feedback  implements java.io.Serializable {


     private Integer idfeedback;
     private String fname;
     private String lname;
     private String email;
     private String phone;
     private String feedback;

    public Feedback() {
    }

    public Feedback(String fname, String lname, String email, String phone, String feedback) {
       this.fname = fname;
       this.lname = lname;
       this.email = email;
       this.phone = phone;
       this.feedback = feedback;
    }
   
    public Integer getIdfeedback() {
        return this.idfeedback;
    }
    
    public void setIdfeedback(Integer idfeedback) {
        this.idfeedback = idfeedback;
    }
    public String getFname() {
        return this.fname;
    }
    
    public void setFname(String fname) {
        this.fname = fname;
    }
    public String getLname() {
        return this.lname;
    }
    
    public void setLname(String lname) {
        this.lname = lname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getFeedback() {
        return this.feedback;
    }
    
    public void setFeedback(String feedback) {
        this.feedback = feedback;
    }




}


